### PR TITLE
Add enabled_tabels option

### PR DESCRIPTION
**Pull request by gogochikago**
I would like to have functionality to restrict checks only for special tables.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @gogochikago, thanks for the PR! Can you share more about the use case?

**Comment by gogochikago** [comment]
@ankane Hello! Thanks for reply
Usually projects have small tables that do not need some checks, for example, updating the default value, etc. I would like to be able to select tables on which to include checks

**Comment by gogochikago** [comment]
Hey @ankane, what do you think about it?

**Comment by ankane** [comment]
Hey @gogochikago, sorry for the delay. There are some operations (like removing a column or renaming a table/column) that I think we'd want to keep regardless of table size. Overall, it's a neat idea, but I don't think it's worth the additional complexity.

**Pull request closed without merging**
