### PR TITLE
Disabled databases will still run the migration

### PR DESCRIPTION
**Pull request by jenskdsgn**
Following up on this Issue: https://github.com/ankane/strong_migrations/issues/255

### CODE REVIEW

**Comment by jenskdsgn** [comment]
@ankane any chance we can have this merged?

**Comment by ankane** [comment]
Thanks @jenskdsgn. Merged into the branch, but still not 100% sure this feature will be included.

**Comment by SergeyKolenko** [comment]
@ankane I'm also need this feature! Can you release it?

**Comment by pnikrat-jt** [comment]
@ankane Can we have this feature released? We could really use an option to ignore the checks in clickhouse migrations. Rails multi-database feature has already been out for some time, having flexibility to apply the gem only for certain DBs would be beneficial to many I think

**Pull request merged**
