### PR TITLE
add_reference support

### PR DESCRIPTION
**Pull request by bartoszkopinski**

### CODE REVIEW

**Comment by ankane** [comment]
Looks great, and complete with tests!! 💯  Thanks @bartoszkopinski

**Comment by ankane** [comment]
It looks like `index: true` is the default value for Rails 5+. However, this won't raise an error if the `index` option is omitted.

**Comment by ankane** [comment]
Fixed here: https://github.com/ankane/strong_migrations/commit/fb30970b0e9e6c9ec48deba47b48adb60dbbb36d

**Comment by bartoszkopinski** [comment]
@ankane thanks 👍

**Pull request merged**
